apiVersion: v1
kind: Secret
metadata:
  name: redis-cloud-secret
  namespace: default
type: Opaque
stringData:
  host: "redis-19088.c305.ap-south-1-1.ec2.cloud.redislabs.com"
  port: "19088"
  username: "default"
  password: "gOhioz4jSQyNLpXkueEZaAK7BlNZTBFX"  # Replace with your password
